<?php
  function findAndReplace_menu() {
      $items['find_and_replace'] = array(
        'title' => 'Sandwich Find and Replace',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('findAndReplace_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
      );
      $items['find_and_replace_success'] = array(
        'title' => 'Here\'s Your New Phrase!',
        'page callback' => 'findAndReplaceResults',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
      );
      return $items;
  }

  function findAndReplace_form() {
    $form['word'] = array(
      '#title' => 'Enter a word you want replaced',
      '#type' => 'textfield',
      '#required' => TRUE,
    );
    $form['phrase'] = array(
      '#title' => 'Enter a Phrase with that word in it',
      '#type' => 'textarea',
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Check You Out!!',
    );
    return $form;
  }

  function findAndReplace_form_submit($form, &$form_state) {
    $_SESSION['word'] = $form_state['values']['word'];
    $_SESSION['phrase'] = $form_state['values']['phrase'];

    $form_state['redirect'] = 'find_and_replace_success';

  }

  function findAndReplaceResults() {
    $phrase = $_SESSION['phrase'];
    $word = $_SESSION['word'];
    // $new_string = str_replace($word, 'sandwich', $phrase);
    $new_string = findAndReplace($word, $phrase);

    return
      '<p>Original Phrase: ' . $phrase .
      '<br>' .
      'Original Word: ' . $word .
      '<br>' .
      'New Phrase: ' . $new_string .
      '</p>';
  }

  function findAndReplace($word, $phrase) {
    $new_string = str_replace($word, 'sandwich', $phrase);

    return $new_string;
  }
