<?php
  function findAndReplace_menu() {
      $items['find_and_replace'] = array(
        'title' => 'Sandwich Find and Replace',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('findAndReplace_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
      );
      $items['find_and_replace_success'] = array(
        'title' => 'Here\'s Your New Phrase!',
        'page callback' => 'findAndReplaceResults',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
      );
      return $items;
  }

  function findAndReplace_form() {
    $form['word'] = array(
      '#title' => 'Enter a word you want replaced',
      '#type' => 'textfield',
      '#required' => TRUE,
    );
    $form['phrase'] = array(
      '#title' => 'Enter a Phrase with that word in it',
      '#type' => 'textarea',
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Check You Out!!',
    );
    return $form;
  }

  function findAndReplace_form_submit($form, &$form_state) {
    $word = $form_state['values']['word'];
    $phrase = $form_state['values']['phrase'];
    $new_string = str_replace($word, 'sandwich', $phrase);
    $_SESSION['new_string'] = $new_string;
    $form_state['redirect'] = 'find_and_replace_success';
  }

  function findAndReplaceResults() {
    $new_string = $_SESSION['new_string'];
    return '<p>Here is your hilarious phrase:<br><strong>' . $new_string . '</strong></p>';
  }
